### ISSUE TITLE
Can't save images

### ISSUE THREAD

**Issue by t-ae** [koher/EasyImagy#15]
Sample project:
https://github.com/t-ae/EasyImagySaveExperiment

I'm trying to save `Image` via `NSImage`/`CGImage`.
https://github.com/t-ae/EasyImagySaveExperiment/blob/master/EasyImagySaveExperiment/ViewController.swift#L21-L25

Then this `NSImage`'s `tiffRepresentation` returns nil with error message below,
> CGImageDestinationFinalize failed for output type 'public.tiff'

And `CGImage` also doesn't generate png data.
I suspect [this property](https://github.com/koher/EasyImagy/blob/master/EasyImagy/ImageCoreGraphics.swift#L100-L121) has a bug.

**Comment by koher** [comment]
Fixed by #16 .
