### ISSUE TITLE
Build error in Xcode10 beta

### ISSUE THREAD

**Issue by hardW** [koher/EasyImagy#26]
On Xcode 10.0 beta4 I've got two errors `Invalid redeclaration of 'countableRange(from:relativeTo:)'` for `internal func countableRange(from range: Range<Int>, relativeTo collection: CountableRange<Int>) -> CountableRange<Int>` and `internal func countableRange(from range: ClosedRange<Int>, relativeTo collection: CountableRange<Int>) -> CountableRange<Int>` in Util.swift

With the implementation of [SE-0143 Conditional conformances](https://github.com/apple/swift-evolution/blob/master/proposals/0143-conditional-conformances.md) in Swift 4.2, CountableRange and CountableClosedRange are not separate types relative to Range, ClosedRange, but their type aliases.

**Comment by hardW** [comment]
I actually don't get what for are those last 4 `internal func countableRange(from range:...` functions in Util.swift
Since after their deletion it compiles ok in both XCode 9 and 10

**Comment by johndpope** [comment]
<img width="719" alt="screen shot 2018-08-21 at 11 22 03 am" src="https://user-images.githubusercontent.com/289994/44411414-75522400-a534-11e8-99c5-b154ede02fa3.png">
@koher - what to do....

**Comment by johndpope** [comment]
<img width="778" alt="screen shot 2018-08-21 at 11 23 49 am" src="https://user-images.githubusercontent.com/289994/44411529-b1858480-a534-11e8-8d15-e8e3db8651ff.png">

**Comment by koher** [comment]
@hardW @johndpope 
Thanks for reporting! I'll fix it.

**Comment by johndpope** [comment]
hack 
github "johndpope/EasyImagy" "0.5.1"

**Comment by koher** [comment]
@hardW @johndpope 

Hi. I checked it and found that the problems had been fixed in 69adfd044e8d6c1e6543705d21e6559ae4c82c3f #25 by @Dschee. Please use the ~~[swift-4.2](https://github.com/koher/EasyImagy/tree/swift-4.2)~~ [dev-0.6.0](https://github.com/koher/EasyImagy/tree/dev-0.6.0) branch for Xcode 10 beta.

I checked that `swift test` and "Product > Test" for iOS with Xcode 10.0 beta 6 passed.

**Comment by koher** [comment]
@hardW 

> Since after their deletion it compiles ok in both XCode 9 and 10

They were unused and I removed them in 45f37ab2c308a2fd37d60c7838670623ce2eed37. Thanks for pointing it out.

**Comment by koher** [comment]
Now [0.5.0](https://github.com/koher/EasyImagy/releases/tag/0.5.0) also supports Swift 4.2.
