### ISSUE TITLE
thoughts on supporting terminal line app

### ISSUE THREAD

**Issue by johndpope** [koher/EasyImagy#34]
I'm reviewing a couple of repos that are using tensorflow for swift as a command line app.

I'd like to plug in EasyImagy but unfortuantely - including frameworks with terminal line apps - isn't so supported. 

A couple of options came to mind 

1) attempt to leverage marathon for using easyimagy
https://github.com/JohnSundell/Marathon/

2)  cherry picking code into a single include file. (may sound bizarre / but consider - no pod - just spit out code and concatenate into a versioned file. )

https://github.com/JulienViguier/CNN_Swift4TensorFlow/blob/master/model.swift
https://github.com/saschaschramm/SwiftReinforce/blob/master/SwiftReinforce/Common/Utilities.swift#L55

//CNN_Swift4TensorFlow

```swift
struct Pixel {
    var r: Float
    var g: Float
    var b: Float
    var a: Float
    var row: Int
    var col: Int
    
    init(r: UInt8, g: UInt8, b: UInt8, a: UInt8, row: Int, col: Int) {
        self.r = Float(r)
        self.g = Float(g)
        self.b = Float(b)
        self.a = Float(a)
        self.row = row
        self.col = col
    }
}

func pixelToFloat(_pixelTab: [[Pixel]]) -> [Float] {
    var tab: [Float] = []
    for (_, row) in _pixelTab.enumerated() {
        for (_, cell) in row.enumerated() {
            tab.append(Float(cell.r/255.0))
            tab.append(Float(cell.g/255.0))
            tab.append(Float(cell.b/255.0))
        }
    }
    return tab
}

```

current solution for swift interfacing to python. 
```swift
func renderPixels(_ pixels: [UInt8], rows: Int, cols: Int) {
    let sys = Python.import("sys")
    let np = Python.import("numpy")
    let path = "\(NSHomeDirectory())/gym/lib/python2.7/site-packages/"
    sys.path.append(path)
    let image = Python.import("PIL.Image")
    
    let foo = np.array(pixels).reshape([rows,cols])
    let img = image.fromarray(np.uint8(foo))
    img.show()
}
```

**Comment by johndpope** [comment]
<img width="2040" alt="screen shot 2018-09-11 at 1 16 49 pm" src="https://user-images.githubusercontent.com/289994/45376105-f85f1b00-b5c4-11e8-996f-3c1147824b35.png">
so naive approach to copy in files didn't go so well.

**Comment by koher** [comment]
Hi, now it can be used from command line and Linux.

https://travis-ci.org/koher/EasyImagy/builds/430938037

However the functionalities depending on UIKit/AppKit/CoreGraphics, e.g. loading images, conversions from/to `Data` and drawing onto images using CoreGraphics, are not available on Linux.
