### ISSUE TITLE
Memory leak on creating data from image

### ISSUE THREAD

**Issue by dastrobu** [koher/EasyImagy#38]
First of all, great library!
There seems so be a memory leak when creating data from images. This causes some trouble in one of my apps. To reproduce, do the following
```
        for _ in 0..<100 {
            let image = Image<UInt8>(width: 1, height: 1, pixels: [0])
            let _ = image.data(using: .png)!
        }
```
When setting a breakpoint after the loop and investigate the memory of core graphics one will find all the images, see screenshot.
![screenshot 2018-12-12 at 01 51 10](https://user-images.githubusercontent.com/1847260/49839884-4bf22800-fdb1-11e8-9a69-c7714eac9625.png)

So what happens in the `image.data` is basically the following:
```
            let data: [UInt8] = [0, 0, 0, 0]
            let provider: CGDataProvider = CGDataProvider(data: Data(
                bytes: UnsafeMutableRawPointer(mutating: data),
                count: 4
            ) as CFData)!

            let cgImage = CGImage(
                width: 1,
                height: 1,
                bitsPerComponent: 1 * 8,
                bitsPerPixel: 4 * 8,
                bytesPerRow: 4 * 1,
                space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGBitmapInfo(),
                provider: provider,
                decode: nil,
                shouldInterpolate: false,
                intent: CGColorRenderingIntent.defaultIntent
            )!

            let imageRep: NSBitmapImageRep = NSBitmapImageRep(cgImage: cgImage)
            imageRep.size = CGSize(width: CGFloat(1), height: CGFloat(1))
            
            // memory leak only with the following line
            let _ = imageRep.representation(using: .png, properties: [:])
```
This self contained block of code does basically the same as `image.data` and is reproducing the memory leak (replace the body of the for loop, and you will find the same leak). So the line of code, causing the trouble is the last one. When removing the last line, the memory leak is gone. 

Unfortunately, I have no idea what is wrong with this code.

**Comment by dastrobu** [comment]
I had some further investigations and created a bug for Swift itself [NSBitmapImageRep.representation(using: .png, properties: [:]) causing memory leak on CGImage](https://bugs.swift.org/browse/SR-9512). Although it was rejected, it helped me to understand what the problem is and how to solve it. One needs to wrap the call to `representation(using: .png, properties: [:])` in a `autoreleasepool`.
Concerning EasyImagy one could leave the usage of `autoreleasepool` to the caller of `.data(using: .png)`, which solves the issue. However, since the usage of `representation(using: .png, properties: [:])` is an implementation detail of EasyImagy, my opinion is that the `autoreleasepool` should be aded to the library itself, so no one needs to worry about allocation problems. 
I created a pull request, solving the issue: https://github.com/koher/EasyImagy/pull/39. Feel free to merge it, if you like the solution.

**Comment by koher** [comment]
@dastrobu 

~~Hi, I think it is better that users of the library adds `autoreleasepool` as necessary in the following way than `autoreleasepool` is added to the library.~~

```swift
for _ in 0..<100 {
    let image = Image<UInt8>(width: 1, height: 1, pixels: [0])
    autoreleasepool {
        let _ = image.data(using: .png)!
    }
}
```

**Comment by koher** [comment]
@dastrobu 

I rethought it and concluded that EasyImagy encapsulates implementations using Obj-C frameworks and so it is natural to add `autoreleasepool` to the library.
