### ISSUE TITLE
Release on CocoaPods?

### ISSUE THREAD

**Issue by gaudecker** [koher/EasyImagy#4]
This library looks to be just what I need. Are you planning to release this on CocoaPods?

**Comment by koher** [comment]
Yes, I will. Not yet just because I've never used CocoaPods and I need to learn something about it to test if EasyImagy can be installed through CocoaPods correctly.

**Comment by koher** [comment]
I have decided that EasyImagy does not support CocoaPods because SPM has been released. It will support SPM instead.
