### ISSUE TITLE
Infinite loop in Xcode 10.2?

### ISSUE THREAD

**Issue by hardW** [koher/EasyImagy#41]
<img width="1472" alt=" " src="https://user-images.githubusercontent.com/5688633/54998865-17c21080-500a-11e9-9565-5d64ef717b54.png">

**Comment by hopperj** [comment]
I'm having this same problem as of updating to Xcode: Version 10.2 (10E125). I'd post a screenshot but it'd be identical to above.

Looks like it was triggered when I do:
let result = Image<RGBA<UInt8>>(uiImage: self.inputImage!).map { $0.blue }

**Comment by koher** [comment]
@hardW @hopperj 

Thank you for reporting errors. Please try [0.6.0](https://github.com/koher/swift-image/releases/tag/0.6.0).
