### ISSUE TITLE
Using the library on Linux

### ISSUE THREAD

**Issue by fappelman** [koher/EasyImagy#49]
I am trying to compile the package on Linux which fails. I am aware that you are not claiming compatibility with Linux but was hoping that you may know a quick fix that would address the below compilation errors.

First of all I am using it as follows:

```swift
func imageDimensions(fromData data: Data) -> (width: Int, height: Int) {
   if let image = Image<RGBA<UInt8>>(data: data) {
        let width = image.width
        let height = image.height
        return (width: width, height: height)
    }
    return (width: -1, height: -1)
}
```
This method works fine on macOS. 

Then when I compile this on Linux I get the following compilation errors:

```log
/project/.build-linux/checkouts/Mercury/Sources/Mercury/ImageDimensions.swift:26:38: 
error: extraneous argument label 'data:' in call
    if let image = Image<RGBA<UInt8>>(data: data) {
                                     ^~~~~~~

/project/.build-linux/checkouts/Mercury/Sources/Mercury/ImageDimensions.swift:26:20: 
error: initializer 'init(_:)' requires the types 'RGBA<UInt8>' 
and 'UInt8' be equivalent
    if let image = Image<RGBA<UInt8>>(data: data) {
                   ^
EasyImagy.ImageProtocol:6:12: note: where 'Self.Element' = 'RGBA<UInt8>', 
'I.Element' = 'UInt8'
    public init<I>(_ image: I) where I : ImageProtocol, Self.Element == I.Element
           ^
/project/.build-linux/checkouts/Mercury/Sources/Mercury/ImageDimensions.swift:26:20: 
error: initializer 'init(_:)' requires that 'Data' conform to 'ImageProtocol'
    if let image = Image<RGBA<UInt8>>(data: data) {
                   ^
EasyImagy.ImageProtocol:6:12: note: where 'I' = 'Data'
    public init<I>(_ image: I) where I : ImageProtocol, Self.Element == I.Element
           ^
```
Based on the above compilation errors, could you perhaps give a hint on how to fix this?

**Comment by fappelman** [comment]
I think it it because the package relies on AppKit. Please ignore my question.

**Comment by erf** [comment]
@koher do you have any plans to support linux? i would love an image library for server side swift ..

**Comment by fappelman** [comment]
That was the reason for my question in the first place. I ended up using:
```
       .package(url: "https://github.com/twostraws/SwiftGD.git", from: "2.0.0"),
```

This ain't a pure Swift solution but relies on install libGD on Linux/MacOS.

You can read about it on this [page](https://www.hackingwithswift.com/articles/87/how-to-wrap-a-c-library-in-swift) as well.

**Comment by erf** [comment]
@fappelman thanks, i will probably look into that until we have something like `swift-image` supported on linux. Are you happy with SwiftGD, performance etc? I would like to use it to resize images.

**Comment by fappelman** [comment]
I did not really do performance measurements. All I can say is that the time spent in GD it is not noticeable to me.
