### ISSUE TITLE
Does this work with Xcode 8 yet?

### ISSUE THREAD

**Issue by chaodoze** [koher/EasyImagy#7]
carthage update returns:
The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/<xxx>/Carthage/Checkouts/EasyImagy/EasyImagy.xcodeproj -scheme EasyImagy-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

**Comment by koher** [comment]
Sorry, I haven't updated it for Xcode8/Swift3. I will do it in a week.

**Comment by chaodoze** [comment]
thank you!

**Comment by koher** [comment]
Migrated to Swift 3.0. Please check the `swift-3` branch.
